package {
    location: "http://coapp.org/repository/${OutputFilename}";
    feed: "http://coapp.org/repository/packages.atom.xml";
    publisher: "Outercurve Foundation, CoApp Project";
}

identity[CoApp Project] {
    name : "CoApp Project, Outercurve Foundation";
    email: "coapp@coapp.org";
    website: "http://coapp.org";
}

identity[Elizabeth M Smith] {
    name : "Elizabeth M Smith, Developer";
    email: "auroraeosrose@gmail.com";
    website: "http://emsmith.net";
}